[[redirects]]
  from = "/api/contentful/:splat"
  to = "https://cdn.contentful.com/:splat"
  status = 200
  force = true
  headers = {Authorization: "Bearer 3cbf6e53e87bef10a885bb99f46c31398f4808a4aa458887b629725294943d9d"}
