[[redirects]]
  from = "/api/contentful-delivery/*"
  to = "https://cdn.contentful.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/contentful-management/*"
  to = "https://api.contentful.com/:splat"
  status = 200
  force = true
