[build]
  functions = "dist-functions"
  command = "npm run deploy"

[[redirects]]
  from = "/api/contentful/*"
  to = "https://cdn.contentful.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200
